---
variables:
  DISTRIBUTION_VER: "stretch"

image: docker.git.sos.ethz.ch/isg/debian-ci-base-int:$DISTRIBUTION_VER

cache:
  paths:
    - 'target/'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - apt update || /bin/true
    - apt install -y --no-install-recommends maven-debian-helper maven || /bin/true
  script:
    - mvn compile

build-package:
  stage: build
  before_script:
    - apt update || /bin/true
    - apt install -y --no-install-recommends maven-debian-helper maven || /bin/true
  script:
    - dpkg-buildpackage -b -us -uc
    - mkdir debbuild
    - mv ../*.deb debbuild/
  artifacts:
    paths:
      - debbuild/*
  only:
    - tags

test:
  stage: test
  before_script:
    - apt update || /bin/true
    - apt install -y --no-install-recommends maven-debian-helper maven || /bin/true
  script:
    - mvn test

deploy_to_apt:
  stage: deploy
  script:
    - echo "Deploying package to $CI_APT_PREFIX prefix and $DISTRIBUTION_VER version"
    - sudo -u repo aptly repo add $CI_APT_REPO debbuild/*.deb
    - sudo -u repo aptly publish update $DISTRIBUTION_VER $CI_APT_PREFIX
  only:
    - tags
  tags:
    - apt